# Read and Prepare the Data (1 points)

In [22]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from sklearn.model_selection import train_test_split

In [23]:
data = pd.read_csv("data.csv")

In [24]:
data.shape

(302, 14)

In [25]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1


In [26]:
y = data['target']
x = data.drop('target', axis=1)

In [27]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3)

In [28]:
#Target variables need to be an array with integer type
train_y = np.array(train_y)
test_y = np.array(test_y)

train_y = train_y.astype(np.int32)
test_y = test_y.astype(np.int32)


In [29]:
#Check the first 10 values of the train_y data set
train_y[0:10]

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1])

In [30]:
#Convert input variables to a 2-D array with float data type
train_x= np.array(train_x)
test_x= np.array(test_x)

train_x = train_x.astype(np.float32)
test_x = test_x.astype(np.float32)

In [31]:
train_x

array([[39.,  0.,  2., ...,  2.,  0.,  2.],
       [39.,  1.,  0., ...,  1.,  0.,  3.],
       [42.,  0.,  2., ...,  1.,  0.,  2.],
       ...,
       [42.,  1.,  0., ...,  2.,  0.,  2.],
       [42.,  1.,  1., ...,  2.,  0.,  2.],
       [57.,  1.,  1., ...,  2.,  1.,  2.]], dtype=float32)

In [32]:
#Keras expects a different input format:
#Data needs to have 3 dimensions

train_x = np.reshape(train_x, (train_x.shape[0], train_x.shape[1], 1))
test_x = np.reshape(test_x, (test_x.shape[0], test_x.shape[1], 1))


In [33]:
train_x.shape, train_y.shape

((211, 13, 1), (211,))

In [34]:
train_x

array([[[39.],
        [ 0.],
        [ 2.],
        ...,
        [ 2.],
        [ 0.],
        [ 2.]],

       [[39.],
        [ 1.],
        [ 0.],
        ...,
        [ 1.],
        [ 0.],
        [ 3.]],

       [[42.],
        [ 0.],
        [ 2.],
        ...,
        [ 1.],
        [ 0.],
        [ 2.]],

       ...,

       [[42.],
        [ 1.],
        [ 0.],
        ...,
        [ 2.],
        [ 0.],
        [ 2.]],

       [[42.],
        [ 1.],
        [ 1.],
        ...,
        [ 2.],
        [ 0.],
        [ 2.]],

       [[57.],
        [ 1.],
        [ 1.],
        ...,
        [ 2.],
        [ 1.],
        [ 2.]]], dtype=float32)

# Find the baseline (0.5 point)

In [35]:
data['target'].value_counts()/len(data)

target
1    0.543046
0    0.456954
Name: count, dtype: float64

# Build a cross-sectional shallow model using Keras (with only one hidden layer) (2 points)

In [44]:
model = Sequential([
    Input(shape=[80, 1]),       # Define the input shape using Input layer
    Flatten(),                  # Flatten the input
    Dense(1, activation='relu'),# First Dense layer with ReLU activation
    Dense(5, activation='softmax') # Output layer with softmax activation
])

In [38]:
# Setting random seeds for reproducibility
np.random.seed(89)
tf.random.set_seed(89)

In [42]:
# Load and preprocess data
data = pd.read_csv("data.csv")
y = data['target']
x = data.drop('target', axis=1)

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3)

In [43]:
# Ensure target variables are arrays with integer type
train_y = np.array(train_y).astype(np.int32)
test_y = np.array(test_y).astype(np.int32)

In [45]:
# Convert input variables to a 2-D array with float data type
train_x = np.array(train_x).astype(np.float32)
test_x = np.array(test_x).astype(np.float32)


In [46]:
# Check the shape of train_x and test_x
print("Shape of train_x before reshaping:", train_x.shape)
print("Shape of test_x before reshaping:", test_x.shape)


Shape of train_x before reshaping: (211, 13)
Shape of test_x before reshaping: (91, 13)


# Build a cross-sectional deep model using Keras (with two or more hidden layers) (2 points)

In [52]:
# Define the model
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[80, 1]),        # Define the input shape using Input layer
    keras.layers.Dense(1, activation='relu'),         # First Dense layer with ReLU activation
    keras.layers.Dense(5, activation='softmax')       # Output layer with softmax activation
])


In [55]:
# Define the optimizer
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)


In [58]:

# Compile the model
# If multiclass, use "sparse_categorical_crossentropy" as the loss function
model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])


# Build a sequential shallow LSTM Model (with only one LSTM layer) (2 points)

In [62]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    
    keras.layers.LSTM(15, input_shape=[n_steps, n_inputs]),
    keras.layers.Dense(5, activation='softmax')])

In [63]:
np.random.seed(56)
tf.random.set_seed(56)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=50,
                   validation_data = (test_x, test_y))

Epoch 1/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 5s 114ms/step - accuracy: 0.2280 - loss: 1.3572 - val_accuracy: 0.4615 - val_loss: 0.9767
Epoch 2/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4781 - loss: 0.9131 - val_accuracy: 0.6923 - val_loss: 0.7317
Epoch 3/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7563 - loss: 0.6944 - val_accuracy: 0.7143 - val_loss: 0.6189
Epoch 4/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7658 - loss: 0.5830 - val_accuracy: 0.7033 - val_loss: 0.5644
Epoch 5/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7832 - loss: 0.5134 - val_accuracy: 0.6813 - val_loss: 0.6709
Epoch 6/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6876 - loss: 0.5727 - val_accuracy: 0.7473 - val_loss: 0.5593
Epoch 7/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7593 - loss: 0.4779 - val_accuracy: 0.7143 - val_loss: 0.5843
Epoch 8/50
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7710 - loss: 0.4658 - val_accuracy: 0.7253 - val_loss: 0.6063

In [64]:
# evaluate the model

LSTM_heart_rate = model.evaluate(test_x, test_y, verbose=0)

LSTM_heart_rate

# In results, first is loss, second is accuracy

[0.638545572757721, 0.7582417726516724]

In [65]:
# extract the accuracy from model.evaluate

print("%s: %.2f" % (model.metrics_names[0], LSTM_heart_rate[0]))
print("%s: %.2f%%" % (model.metrics_names[1], LSTM_heart_rate[1]*100))

loss: 0.64
compile_metrics: 75.82%


# Build a sequential deep LSTM Model (with only two LSTM layers) (2 points)

In [66]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    

    keras.layers.LSTM(10, return_sequences=True, input_shape=[n_steps, n_inputs]),
    keras.layers.LSTM(10),
    keras.layers.Dense(5, activation='softmax')
])

In [67]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=10,
                   validation_data = (test_x, test_y))

Epoch 1/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 8s 169ms/step - accuracy: 0.5253 - loss: 1.3154 - val_accuracy: 0.5385 - val_loss: 0.8810
Epoch 2/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5253 - loss: 0.8358 - val_accuracy: 0.5385 - val_loss: 0.7391
Epoch 3/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5253 - loss: 0.7338 - val_accuracy: 0.5385 - val_loss: 0.7111
Epoch 4/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5253 - loss: 0.7119 - val_accuracy: 0.5385 - val_loss: 0.7009
Epoch 5/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5253 - loss: 0.7026 - val_accuracy: 0.5385 - val_loss: 0.6957
Epoch 6/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5253 - loss: 0.6950 - val_accuracy: 0.5385 - val_loss: 0.6877
Epoch 7/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6143 - loss: 0.6789 - val_accuracy: 0.5604 - val_loss: 0.6656
Epoch 8/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6457 - loss: 0.6482 - val_accuracy: 0.6813 - val_loss: 0.6362

In [68]:
# evaluate the model

two_LSTM_heart_rate = model.evaluate(test_x, test_y, verbose=0)

two_LSTM_heart_rate

# In results, first is loss, second is accuracy

[0.5986900925636292, 0.7032967209815979]

In [69]:
# extract the accuracy from model.evaluate

print("%s: %.2f" % (model.metrics_names[0], two_LSTM_heart_rate[0]))
print("%s: %.2f%%" % (model.metrics_names[1], two_LSTM_heart_rate[1]*100))

loss: 0.60
compile_metrics: 70.33%


# Build a sequential shallow GRU Model (with only one GRU layer) (2 points)

In [70]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    keras.layers.GRU(25, input_shape=[n_steps, n_inputs]),
    keras.layers.Dense(5, activation='softmax')
])

In [71]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20,
                   validation_data = (test_x, test_y))

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 5s 108ms/step - accuracy: 0.2406 - loss: 1.7347 - val_accuracy: 0.5385 - val_loss: 0.8787
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.5129 - loss: 0.8153 - val_accuracy: 0.5385 - val_loss: 0.7109
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5386 - loss: 0.6880 - val_accuracy: 0.5385 - val_loss: 0.6825
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6158 - loss: 0.6537 - val_accuracy: 0.5604 - val_loss: 0.6761
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6673 - loss: 0.6292 - val_accuracy: 0.6923 - val_loss: 0.6555
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7072 - loss: 0.5924 - val_accuracy: 0.7033 - val_loss: 0.6504
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7438 - loss: 0.5605 - val_accuracy: 0.7143 - val_loss: 0.6663
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7460 - loss: 0.5530 - val_accuracy: 0.7143 - val_loss: 0.6418

In [74]:
# evaluate the model

gru_heart_beat = model.evaluate(test_x, test_y, verbose=0)

gru_heart_beat 

# In results, first is loss, second is accuracy

[0.5693512558937073, 0.7252747416496277]

In [75]:
# extract the accuracy from model.evaluate

print("%s: %.2f" % (model.metrics_names[0], gru_heart_beat[0]))
print("%s: %.2f%%" % (model.metrics_names[1], gru_heart_beat[1]*100))


loss: 0.57
compile_metrics: 72.53%


# Build a sequential deep GRU Model (with only two GRU layers) (2 points)

In [76]:
n_steps = 80
n_inputs = 1

model = keras.models.Sequential([
    keras.layers.GRU(25, return_sequences=True, input_shape=[n_steps, n_inputs]),
    keras.layers.GRU(15),
    keras.layers.Dense(5, activation='softmax')
])

In [77]:
np.random.seed(42)
tf.random.set_seed(42)

optimizer = keras.optimizers.Nadam(learning_rate=0.01)

model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=['accuracy'])

history = model.fit(train_x, train_y, epochs=20,
                   validation_data = (test_x, test_y))

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - accuracy: 0.2978 - loss: 1.4721 - val_accuracy: 0.5385 - val_loss: 0.8863
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4979 - loss: 0.8445 - val_accuracy: 0.5385 - val_loss: 0.7493
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5344 - loss: 0.7237 - val_accuracy: 0.5385 - val_loss: 0.7129
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5806 - loss: 0.6650 - val_accuracy: 0.6593 - val_loss: 0.7021
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6822 - loss: 0.6164 - val_accuracy: 0.7143 - val_loss: 0.6987
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7575 - loss: 0.5636 - val_accuracy: 0.6703 - val_loss: 0.6873
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7915 - loss: 0.5146 - val_accuracy: 0.6703 - val_loss: 0.6813
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7827 - loss: 0.4917 - val_accuracy: 0.6923 - val_loss: 0.6710

In [78]:
# evaluate the model

GRU_Model = model.evaluate(test_x, test_y, verbose=0)

GRU_Model

# In results, first is loss, second is accuracy

[0.46736136078834534, 0.791208803653717]

In [79]:
# extract the accuracy from model.evaluate

print("%s: %.2f" % (model.metrics_names[0], GRU_Model[0]))
print("%s: %.2f%%" % (model.metrics_names[1], GRU_Model[1]*100))


loss: 0.47
compile_metrics: 79.12%


# Discussion

## List the test values of each model you built (0.5 points)

In [81]:
#Though there is not much difference between the Sequential shallow GRU Model and Sequential deep GRU Model, comaparitively, the Sequential deep GRU Model has slightly less loss and more accuracy. 

## Which model performs the best and why? (0.5 points) 
## How does it compare to baseline? (0.5 points)



In [83]:
#When compared with the baseline accuracy (58.02), the sequential deep GRU model has approximately 35% more accuracy.